group: stable
services:
  - postgresql

script:
  - dpkg -l | grep postgis
  - psql -U postgres -c "create extension postgis"
  
matrix:
  include:
    - os: linux
      sudo: false
    - os: linux
      sudo: required
  


