dist: trusty
sudo: required
install: skip
language: generic

script:
  - sh -e /etc/init.d/xvfb start
  - sh -e /etc/init.d/xvfb status
  - sh -e /etc/init.d/xvfb stop
  - sh -e /etc/init.d/xvfb status
  

matrix:
 include:
    - group: stable
    - group: deprecated-2017Q4
  
