dist: trusty
sudo: required
language: python
virtualenv:
  system_site_packages: true
group: dev

install: skip

script:
  - python --version
  - python3 --version
  - pip freeze
  
matrix:
  include:
    - python: pypy
    - python: pypy3
  
