os: linux
dist: trusty
group: stable
language: ruby
    
install: skip

matrix:
  include:
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
    - script: 
        - sudo apt-get update
        - wget http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg
