dist: trusty
sudo: required
language: java

script:
  - java -version
  - echo $JAVA_HOME

matrix:
  include:
    - group: edge
      env: JAVA=ibmjava8
      jdk: ibmjava8
    - group: edge
      env: JAVA=openjdk7
      jdk: openjdk7
