os: linux
dist: trusty
group: stable
language: python
python: 3.5
sudo: required
    
install: skip

script:
    - gpg --version
    - gpg --keyserver hkp://pool.sks-keyservers.net --recv A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
