dist: trusty
sudo: required
group: edge
install: skip

script:
  - echo "Hello!"
  - nvm --version

matrix:
  include:
    - language: __amethyst__
    - language: __garnet__
    - language: __connie__
  
