dist: trusty
sudo: required
language: generic

install: skip

script:
  - yarn --version
  - nvm --version
  - gimme --version
  - rabbitmq-server --version

matrix:
  include:
    - group: stable
    - group: dev
  
