dist: trusty
sudo: required
language: python
virtualenv:
  system_site_packages: true
group: dev

install: skip

script:
  - python --version
  - pip freeze
  
matrix:
  include:
    - python: 2.7
    - python: 3.6
  
