dist: trusty
sudo: required
language: python

install: skip

script:
  - pyenv versions
  - python --version
  
matrix:
  include:
    - python: 2.7
    - python: 2.7.13
    - python: 3.5
    - python: 3.6
  
